#!/usr/bin/env node
'use strict'
const parsingErrorsWarning = `If you get any HTML parsing errors, you can redirect stderr:
    $0 ... 2>/dev/null`
const hte = require('html-text-extract')
require('core-text-spellcheck-cli')({
	spellChecker: require('core-text-spellcheck'),
	usageMessage: parsingErrorsWarning,
	preProcessor: (text) => hte(text, true)
})()
